/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-06-23 15:32:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN PAGE HEADER-->\r\n");
      out.write("                <div class=\"row-fluid\">\r\n");
      out.write("                    <div class=\"span12\">\r\n");
      out.write("                        <!-- BEGIN PAGE TITLE & BREADCRUMB-->\r\n");
      out.write("                        <h3 class=\"page-title\">\r\n");
      out.write("                            <span>THÀNH VIÊN</span>\r\n");
      out.write("                            <button class=\"btn btn-success pull-right\" data-toggle=\"modal\" data-target=\"#account-modal\">\r\n");
      out.write("                                <i class=\"icon-plus icon-white\"></i> Thêm mới\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </h3>\r\n");
      out.write("                        <!-- END PAGE TITLE & BREADCRUMB-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- END PAGE HEADER-->\r\n");
      out.write("                <!-- BEGIN ADVANCED TABLE widget-->\r\n");
      out.write("                <div class=\"row-fluid\">\r\n");
      out.write("                    <div class=\"span12\">\r\n");
      out.write("                        <!-- BEGIN EXAMPLE TABLE widget-->\r\n");
      out.write("                        <div class=\"widget orange\">\r\n");
      out.write("                            <div class=\"widget-title\">\r\n");
      out.write("                                <h4>\r\n");
      out.write("                                    <i class=\"icon-list-ul\"></i> Danh sách thành viên\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <span class=\"tools\"> <a href=\"javascript:;\" class=\"icon-chevron-down\"></a> <a\r\n");
      out.write("                                        href=\"javascript:;\" class=\"icon-remove\"></a>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <table class=\"table table-striped table-bordered\" id=\"sample_1\">\r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>Họ tên</th>\r\n");
      out.write("                                            <th class=\"hidden-phone\">Email</th>\r\n");
      out.write("                                            <th class=\"hidden-phone\">Điện thoại</th>\r\n");
      out.write("                                            <th class=\"hidden-phone\">Địa chỉ</th>\r\n");
      out.write("                                            <th class=\"hidden-phone\">Acction</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        <tr class=\"odd gradeX\">\r\n");
      out.write("                                            <td>Nguyễn Văn A</td>\r\n");
      out.write("                                            <td class=\"hidden-phone\">nguyenvana@gmail.com</td>\r\n");
      out.write("                                            <td class=\"hidden-phone\">012345678</td>\r\n");
      out.write("                                            <td class=\"center hidden-phone\">02 Mạc Đĩnh Chi - Đa Kao - Q.1 - Tp.HCM</td>\r\n");
      out.write("                                            <td class=\"hidden-phone\">\r\n");
      out.write("                                                <a class=\"btn btn-success\" href=\"thong-ke-thanh-vien.html\">\r\n");
      out.write("                                                    <i class=\"icon-ok\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("                                                <a href=\"chi-tiet-thanh-vien.html\"\r\n");
      out.write("                                                    class=\"btn btn-primary btn-account-edit\">\r\n");
      out.write("                                                    <i class=\"icon-pencil\"></i>\r\n");
      out.write("                                                </a>\r\n");
      out.write("\r\n");
      out.write("                                                <button type=\"button\"\r\n");
      out.write("                                                    class=\"btn btn-danger btn-account-delete\">\r\n");
      out.write("                                                    <i class=\"icon-trash \"></i>\r\n");
      out.write("                                                </button></td>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- END EXAMPLE TABLE widget-->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- END ADVANCED TABLE widget-->\r\n");
      out.write("\r\n");
      out.write("                <!-- MY MODAL -->\r\n");
      out.write("                <div class=\"my-modal\" id=\"account-modal\">\r\n");
      out.write("                    <div class=\"modal-content modal-4\">\r\n");
      out.write("                        <div class=\"widget orange\">\r\n");
      out.write("                            <div class=\"widget-title\">\r\n");
      out.write("                                <h4>Thêm thành viên</h4>\r\n");
      out.write("                                <span class=\"tools\"> <a href=\"javascript:;\" data-dismiss=\"modal\"\r\n");
      out.write("                                        class=\"icon-resize-small modal-close\"></a>\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <form action=\"\" method=\"post\" id=\"frmAccount\">\r\n");
      out.write("                                    <div class=\"row-fluid\">\r\n");
      out.write("                                        <div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("                                            <input type=\"hidden\" class=\"span12\" id=\"account_id\" name=\"account_id\">\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"control-group\">\r\n");
      out.write("                                                <label class=\"control-label\">Email</label>\r\n");
      out.write("                                                <div class=\"controls\">\r\n");
      out.write("                                                    <input type=\"text\" class=\"span12\" id=\"email\" name=\"email\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"control-group password-group\">\r\n");
      out.write("                                                <label class=\"control-label\">Mật khẩu</label>\r\n");
      out.write("                                                <div class=\"controls\">\r\n");
      out.write("                                                    <input type=\"password\" class=\"span12\" id=\"password\" name=\"password\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"control-group password-group\">\r\n");
      out.write("                                                <label class=\"control-label\">Nhập lại mật khẩu</label>\r\n");
      out.write("                                                <div class=\"controls\">\r\n");
      out.write("                                                    <input type=\"password\" class=\"span12\" id=\"c\" name=\"confirm\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"control-group\">\r\n");
      out.write("                                                <label class=\"control-label\">Họ tên</label>\r\n");
      out.write("                                                <div class=\"controls\">\r\n");
      out.write("                                                    <input type=\"text\" class=\"span12\" id=\"fullname\" name=\"fullname\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"control-group\">\r\n");
      out.write("                                                <label class=\"control-label\">Số điện thoại</label>\r\n");
      out.write("                                                <div class=\"controls\">\r\n");
      out.write("                                                    <input type=\"text\" class=\"span12\" id=\"phone\" name=\"phone\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"control-group\">\r\n");
      out.write("                                                <label class=\"control-label\">Địa chỉ</label>\r\n");
      out.write("                                                <div class=\"controls\">\r\n");
      out.write("                                                    <input type=\"text\" class=\"span12\" id=\"address\" name=\"address\">\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"widget-footer\">\r\n");
      out.write("                                        <button type=\"button\" class=\"btn modal-close\" data-dismiss=\"modal\">\r\n");
      out.write("                                            <i class=\"icon-ban-circle icon-white\"></i> Hủy\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <button class=\"btn btn-success\">\r\n");
      out.write("                                            <i class=\"icon-ok icon-white\"></i> Lưu lại\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- END MY MODAL -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
